// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr2s9y_f92Rqv5g5XFHC18-PW2FBnug9s',
    appId: '1:185829213353:web:108e602f1ba97aa05655b8',
    messagingSenderId: '185829213353',
    projectId: 'inventory-app-d737d',
    authDomain: 'inventory-app-d737d.firebaseapp.com',
    storageBucket: 'inventory-app-d737d.firebasestorage.app',
    measurementId: 'G-ZMGMP6B0XD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAbu6s3VPSwWPBZ29gn3XTKMAqUYEQg-I',
    appId: '1:185829213353:android:15f0deeacedeb0855655b8',
    messagingSenderId: '185829213353',
    projectId: 'inventory-app-d737d',
    storageBucket: 'inventory-app-d737d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKQXER1cpr5OdKl_Wykb5I36dr9Jj6TYU',
    appId: '1:185829213353:ios:08b96f555dc8e6a25655b8',
    messagingSenderId: '185829213353',
    projectId: 'inventory-app-d737d',
    storageBucket: 'inventory-app-d737d.firebasestorage.app',
    iosBundleId: 'com.example.inclass15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKQXER1cpr5OdKl_Wykb5I36dr9Jj6TYU',
    appId: '1:185829213353:ios:08b96f555dc8e6a25655b8',
    messagingSenderId: '185829213353',
    projectId: 'inventory-app-d737d',
    storageBucket: 'inventory-app-d737d.firebasestorage.app',
    iosBundleId: 'com.example.inclass15',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr2s9y_f92Rqv5g5XFHC18-PW2FBnug9s',
    appId: '1:185829213353:web:dd17919ae02d35fe5655b8',
    messagingSenderId: '185829213353',
    projectId: 'inventory-app-d737d',
    authDomain: 'inventory-app-d737d.firebaseapp.com',
    storageBucket: 'inventory-app-d737d.firebasestorage.app',
    measurementId: 'G-TB49YMNMFJ',
  );
}
